boostcampwm2023/iOS05-Village

iOS/Village/.swiftlint.yml
iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

- #4
- homebrew로 적용하기로 결정 
- x

[iOS/#4] SwiftLint 적용

---

iOS/Village/Village/Resources/Assets.xcassets/Grey-800.colorset/Contents.json
iOS/Village/Village/Resources/Assets.xcassets/Negative-400.colorset/Contents.json
iOS/Village/Village/Resources/Assets.xcassets/Primary-500.colorset/Contents.json

[iOS/#13] Color Scheme 추가

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village.xcodeproj/xcshareddata/xcschemes/Village.xcscheme

- #22
- Execute in Parallel 옵션 해제

[iOS/#22] 테스트 타겟 설정

---

BE/.prettierrc

- BE prettier 설정
- #30
- 코드의 일관성을 위해 고민

 [BE/#30] ESLint 설정

---

BE/.gitignore
BE/package-lock.json
BE/package.json
BE/src/main.ts
BE/src/utils/swagger.ts

Resolves: #32
- #32
- git clone 후 npm install을 안하고 의존성을 추가하니까 오류가 발생했다.

[BE/#32] Swagger 설정

---

BE/.gitignore
BE/package.json
BE/src/app.module.ts

Resolves: #34
- #34
- 실행 환경별로 다른 환경변수가 작동되도록 설정
환경 별로 어떻게 다르게 설정되게 고민하였다. 그래서 실행될 때 환경변수를 세팅 하고 그 값을 바탕으로 다른 env 파일을 읽어 설정되게 하였다.

[BE/#34] 환경변수 설정

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Common/Constants.swift
iOS/Village/Village/Presentation/CustomView/FloatingButton.swift

- #8 
- 이미지 이름 상수화를 Common 그룹 내 `Constants.swift` 라는 파일에서 enum 타입 `ImageSystemName` 로 시도해봤습니다. 지적해주실 부분이 있다면 남겨주세요
- 우선 별도의 @objc 함수를 추가하지 않고 UIAction 변수를 위에 선언하는 방법으로 해결했습니다.
없음

[iOS#8] Refactor: 리뷰 피드백 반영

---

BE/.gitignore
BE/package-lock.json
BE/package.json
BE/src/app.controller.ts
BE/src/app.module.ts
BE/src/main.ts
BE/src/utils/winston.ts

[BE/#36] Logging 설정

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/PostingRent/PeriodPicker.swift
iOS/Village/Village/Presentation/PostingRent/PostingRentViewController.swift

- #27
- UIDatePicker에서 시간만 사용하는 방식이 존재하지 않아 일별로 관리하도록 수정
- UITextField에 Inset을 주는 방식을 rightView와 leftView를 사용하기보다 겉에 UIView로 감싸 해결.

[iOS#27] 게시글 등록 뷰 구현 및 AutoLayout 적용

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Application/SceneDelegate.swift
iOS/Village/Village/Presentation/Home/HomeCollectionViewCell.swift
iOS/Village/Village/Presentation/Home/HomeViewController.swift
iOS/Village/Village/Presentation/Utils/Extensions/UILabel+SetTitle.swift
iOS/Village/Village/Presentation/Utils/Extensions/UINavigationItem+MakeSFSymbolButton.swift

- #28
- CollectionViewController 적용
- DiffableDataSource 적용
- Compositional Layout 적용
- 피그마 디자인을 참고하여 구현
- 익스텐션을 이용해서 재사용성 고려
- 컬렉션 뷰에는 악세서리 뷰가 없는 것으로 판단하여 임의적으로 뷰를 만들어서 띄워주었다.
- 아직 뷰모델을 작성하지 않아서 임의의 데이터를 뷰에 넣어주었다. 뷰모델을 만들면서 적용할 예정
https://github.com/boostcampwm2023/iOS05-Village/assets/59719500/09e8164a-e134-4b77-9cf2-3fe9300eacc8

[iOS/#28] 홈 뷰 구현 및 AutoLayout 적용

---

iOS/.gitattributes

- #44
- Xcode pbxproj merge conflict를 해결하기 위해 gitattributes를 설정함.

[iOS/#44] .gitattributes 설정

---

iOS/Village/Village/Common/Constants.swift
iOS/Village/Village/Presentation/Home/HomeCollectionViewCell.swift
iOS/Village/Village/Presentation/Home/HomeViewController.swift
iOS/Village/Village/Presentation/Utils/Extensions/UINavigationItem+MakeSFSymbolButton.swift
iOS/Village/Village/Resources/Assets.xcassets/Primary-100.colorset/Contents.json

[iOS/#28] 피드백 수정

---

.github/workflows/be-ci.yml

 [BE/#49] CI 스크립트 작성

---

.github/workflows/be-ci.yml

 [BE/#49] CI 수정

---

.github/workflows/be-ci.yml

[BE/#49] CI 수정 

---

.github/workflows/be-ci.yml

[BE/#49] CI 수정

---

BE/src/app.module.ts
BE/src/post/post.controller.ts
BE/src/post/post.module.ts
BE/src/post/post.service.ts

- #60 
- DB에서 게시글 목록 가져오기
- 데이터 가공해서 API 문서 대로 수정
- 물품 조회 controller 구현

[BE/#60] 물품 조회 API 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Application/SceneDelegate.swift
iOS/Village/Village/Common/Constants.swift
iOS/Village/Village/Presentation/Chat/ChatViewController.swift
iOS/Village/Village/Presentation/MyPage/MyPageViewController.swift

[iOS/#67] TapBarController 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/DetailPost/DetailPostViewController.swift
iOS/Village/Village/Presentation/DetailPost/PostDetailViewController.swift
iOS/Village/Village/Presentation/Home/View/HomeCollectionViewCell.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/Home/ViewModel/PostListItemViewModel.swift

- #65
- 상세 페이지로 넘어갈 때, 값을 어떻게 넘겨줘야될 지 고민.
- 뷰 모델에서 리턴받은 값을 다음 뷰컨트롤러에게 넘겨주는 방식으로 구현

[iOS/#65] 게시글 상세화면으로 이동

---

iOS/Village/Village/Presentation/CustomView/FloatingButton.swift

- #8 
- 멘토링 시간 때 받은 질문에 대한 답변을 수용하여 플로팅 버튼을 UIView 구현체로 변경했습니다.
없음

[iOS/#8] 홈 화면 게시글 등록 Floating Button 구현

---

.github/workflows/BE-CD.yml
.github/workflows/BE-CI.yml

[BE/#49] CD 설정

---

.github/workflows/BE-CD.yml

[BE/#49] CD yml 파일 대상 브랜치 이름 변경

---

.github/workflows/BE-CD.yml

[BE] Fix : CD yml 명령수정

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Application/SceneDelegate.swift
iOS/Village/Village/Common/Constants.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/Search/SearchViewController.swift

- #74
https://github.com/boostcampwm2023/iOS05-Village/assets/59719500/3a4e77c2-f0e0-4269-8c9b-f228f346abe9

[iOS/#74] 검색화면으로 이동

---

iOS/Village/Village/Network/NetworkService.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift

[iOS/#92] NetworkService 코드 리팩토링

---

BE/package-lock.json
BE/package.json
BE/src/post/post.controller.ts
BE/src/post/post.service.ts

[BE/#83] GET /posts/{id} API 구현

---

BE/src/post/post.service.ts

- #109
- filter를 적용하지 않았을 때 요청 글이 나오는 문제 해결
- 쿼리 파람에 따라 where 절을 만드는 로직이 추후 더 길어질것 같아 함수로 분리하였다.

[BE/#109] filter 오류 해결

---

BE/src/post/dto/postCreate.dto.ts
BE/src/post/post.controller.ts
BE/src/utils/price.decorator.ts

- #115
- price에 대한 검증 로직 추가
요청글 여부에 따라 price 값을 다르게 검증해야하기 때문에 커스텀 데코레이터를 만들수 밖에 없었다.

[BE/#115] price에 대한 오류 처리 추가

---

BE/src/app.module.ts
BE/src/config/mysql.config.ts
BE/src/entities/blockPost.entity.ts
BE/src/entities/blockUser.entity.ts
BE/src/entities/user.entity.ts
BE/src/users-block/users-block.controller.ts
BE/src/users-block/users-block.module.ts
BE/src/users-block/users-block.service.ts

- #127 
- 차단하려는 유저가 존재하지 않는 경우, 이미 차단한 경우 등 다양한 경우가 있어서 처리가 빡셌다

[BE/#127] POST /users/block/{id} API 구현

---

BE/src/users-block/users-block.service.ts

[BE/#135] status 타입 오류 수정

---

BE/src/entities/blockUser.entity.ts
BE/src/users-block/users-block.controller.ts
BE/src/users-block/users-block.service.ts

[BE/#137] GET users/block API 구현

---

BE/package-lock.json
BE/package.json
BE/src/entities/user.entity.ts
BE/src/users/users.service.ts
BE/src/utils/hashMaker.ts

- #143 
- 중복이 없어야 하고
- 해시값을 통해서 다른 사람이 유저의 정보를 유추할 수 있으면 안된다
- 8자리 제한

[BE/#143] Feat : hash 생성 함수 구현

---

BE/src/post/post.controller.ts
BE/src/post/post.module.ts
BE/src/post/post.service.ts

- #145
- 차단된 사용자가 작성한 글 필터링
- 차단된 게시글 필터링
- 필터링 부분은 db에서 필터링이 아니라 db에서 가져온후 서버에서 필터링 하게 해주었는데 좋은 방법인지는 잘 모르겠다.

[BE/#145] 게시글 조회시 차단 목록 필터링 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Domain/Network/PostResponseDTO.swift
iOS/Village/Village/Presentation/Home/Model/PostListItem.swift

- #148 
- DTO에서 어떤 정보를 덜어낼지 고민했습니다. 우선 이미지 URL 배열에서 첫 번째 것만 가지도록 했고 (또는 nil), 시작 날짜, 종료 날짜, 상세 내용을 덜어냈습니다.
- 생성자를 통한 변환은 의존하는 관계이므로 추후에 어떻게 느슨하게 연결할지 고민하고 수정해야할 것 같습니다.
없음

[iOS/#148] PostListItem 모델 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Domain/Network/PostListRequestDTO.swift
iOS/Village/Village/Domain/Network/PostListResponseDTO.swift
iOS/Village/Village/Domain/Network/UserResponseDTO.swift
iOS/Village/Village/Presentation/Home/Model/PostListItem.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/Home/ViewModel/HomeViewModel.swift
iOS/Village/Village/Presentation/PostDetail/Custom/PostInfoView.swift
iOS/Village/Village/Presentation/PostDetail/RentDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/RequestDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

[iOS/#147] 게시글 상세 화면 ViewModel 구현

---

BE/src/post/dto/postCreate.dto.ts
BE/src/post/dto/postUpdate.dto.ts
BE/src/post/post.controller.ts
BE/src/post/post.service.ts

[BE/#154] 변수 네이밍 변경

---

BE/src/post/post.service.ts

[BE] Refactor : getPost 변수명 수정

---

BE/src/post/post.service.ts

[BE/#164] findPosts  이미지 배열 처리

---

BE/src/entities/blockPost.entity.ts
BE/src/entities/blockUser.entity.ts
BE/src/entities/post.entity.ts
BE/src/entities/postImage.entity.ts
BE/src/entities/user.entity.ts
BE/src/post/post.service.ts

[BE/#169]  Soft Delete 적용

---

BE/package-lock.json
BE/package.json
BE/src/config/winston.config.ts
BE/src/main.ts
BE/src/post/post.controller.ts
BE/src/utils/httpLogger.interceptor.ts

[BE/#173] API 서버 로그 기록

---

BE/package-lock.json
BE/package.json
BE/src/main.ts
BE/src/post/dto/postUpdate.dto.ts
BE/src/post/post.service.ts

- #142
- 이미지 삭제와 추가를 따로 분리하여 처리하도록 하였다.

[BE/#142] PATCH Post/{id} 구현

---

iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/PostDetail/Custom/PostInfoView.swift

- #178 
없음
https://github.com/boostcampwm2023/iOS05-Village/assets/19406851/ba817ace-6e86-4cc6-86c4-9bb6aad631c0

[iOS/#178] 홈 화면 플로팅 버튼 개선

---

BE/src/app.controller.spec.ts
BE/src/app.controller.ts
BE/src/app.module.ts
BE/src/app.service.ts
BE/src/config/swagger.config.ts
BE/src/entities/blockPost.entity.ts
BE/src/entities/blockUser.entity.ts
BE/src/post/post.controller.ts
BE/src/posts-block/posts-block.service.ts
BE/src/users-block/users-block.service.ts
BE/src/users/users.service.ts
BE/src/utils/httpLogger.interceptor.ts

[BE/#181] API 오류 수정 및 API 문서 연결

---

BE/package-lock.json
BE/package.json
BE/src/app.module.ts
BE/src/login/dto/appleLogin.dto.ts
BE/src/login/login.controller.spec.ts
BE/src/login/login.controller.ts
BE/src/login/login.module.ts
BE/src/login/login.service.spec.ts
BE/src/login/login.service.ts

- #191 
- Apple 로그인 자체가 과정이 어려워서 코드를 작성하는 과정이 힘들었다

[BE/#191] Apple OAuth 구현

---

BE/src/login/login.controller.ts
BE/src/login/login.module.ts
BE/src/main.ts
BE/src/post/post.controller.ts
BE/src/post/post.module.ts
BE/src/posts-block/posts-block.controller.ts
BE/src/posts-block/posts-block.module.ts
BE/src/users-block/users-block.controller.ts
BE/src/users-block/users-block.module.ts
BE/src/users/users.controller.ts
BE/src/users/users.module.ts
BE/src/utils/auth.guard.ts

- #200 
- 모든 컨트롤러에 Guard 를 적용해야 하나 -> 모든 컨트롤러에 적용

[BE/#200] Guard 인가 구현

---

BE/src/login/appleLoginDto.ts
BE/src/login/login.controller.ts
BE/src/login/login.service.ts

- #199
- refresh 토큰을 어떤 방식으로 다시 발급 할지에 대해 고민했다. 발급조건, 토큰 두개를 전부 다 발급해야하는지, db에 토큰을 저장해두는지 등 의 고민을 하였는데 일단은 유효성만 보고 발급 하기로 했다. 아직 db의 컬럼도 없고 사용할 db도 없어서 일단은 추후에 좀 더 보안 수준을 높히기 위해 db에 저장해서 검증하는 방식을 사용할 것 같다.

[BE/#199] 토큰 재발급 로직 구현

---

BE/src/post/post.controller.ts
BE/src/posts-block/posts-block.controller.ts
BE/src/users-block/users-block.controller.ts
BE/src/utils/auth.decorator.ts
BE/src/utils/auth.guard.ts

[BE/#205]  UserHash 데코레이터 구현

---

BE/package-lock.json
BE/package.json
BE/src/app.module.ts
BE/src/chat/chat.controller.ts
BE/src/chat/chat.module.ts
BE/src/chat/chat.service.ts
BE/src/chat/chats.gateway.ts
BE/src/main.ts

[BE/#214] Feat : 채팅 Gateway 설정

---

BE/src/chat/chat.controller.ts
BE/src/chat/chat.module.ts
BE/src/chat/chat.service.ts
BE/src/chat/chats.gateway.ts
BE/src/chat/createRoom.dto.ts
BE/src/entities/chatRoom.entity.ts

- #218
- 무슨 이유로 어떻게 코드를 변경했는지
- 어떤 부분에 리뷰어가 집중해야 하는지
- 기술적 고민

[BE/#218] 채팅방 만들기 구현

---

BE/src/chat/chat.controller.ts
BE/src/chat/chat.service.ts
BE/src/chat/chats.gateway.ts
BE/src/chat/createRoom.dto.ts
BE/src/config/mysql.config.ts
BE/src/entities/chatRoom.entity.ts
BE/src/utils/auth.decorator.ts

- #220 
- 채팅하기를 누르면 채팅방이 있으면 조회, 없으면 채팅방을 되돌려주는 메서드 구현

[BE/#220] Feat : 채팅하기 누르면 채팅방 생성 혹은 조회 구현

---

BE/src/config/mysql.config.ts
BE/src/entities/chat.entity.ts
BE/src/entities/chatRoom.entity.ts
BE/src/entities/user.entity.ts
BE/src/utils/auth.guard.ts

[BE/#229] DB Chat Entity 제작 및 DB 제작

---

BE/package-lock.json
BE/package.json
BE/src/chat/chat.controller.ts
BE/src/chat/chat.module.ts
BE/src/config/mysql.config.ts
BE/src/entities/registrationToken.entity.ts
BE/src/entities/user.entity.ts
BE/src/utils/fcmHandler.ts

[BE/#223] FCM 을 조작할 수 있는 로직 추가

---

iOS/Village/Village/Data/Dummy/ChatRoom.json
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/ViewModel/ChatRoomViewModel.swift
iOS/Village/Village/Socket/WebSocket.swift

- #235
- receive를 할 때, 내가 보낸 데이터에 대해서도 수신이 가능한 줄 알았는데, 아니여서 시간을 낭비했다.
- 소켓 통신간에 발생한 채팅로그에 대해서 뷰모델에 어떻게 주입하면 좋을 지 고민.

[iOS/#235] 채팅 받기 구현

---

BE/src/post/post.controller.ts
BE/src/post/post.service.ts
BE/src/users/users.controller.ts
BE/src/users/users.service.ts

- #208
- 가드에서 권한에 대한 처리를 하고 싶었는데 너무 얽힌 코드가 많아 일단은 서비스 레이어에서 처리. 추후 리펙토링을 해야할 것 같다.
- 차단에 관한 것은 아직 처리 하지 못했다.

[BE/#208] 게시글,사용자 정보 수정 권한 추가

---

BE/src/chat/chat.module.ts
BE/src/chat/chat.service.ts
BE/src/chat/chats.gateway.ts
BE/src/utils/fcmHandler.ts

- #267
- 방에 입장 할 떄 client(Websocket) 객체에 roomId 를 부여하고 연결이 끊어질 때 부여된 roomId를 기준으로 방에서 나올 수 있게 처리 했다.
- 그래서 끊어진 경우는 방에 없기 때문에 방을 확인 하면 보낼 대상이 웹소켓 연결중인지 판단 할 수 있다.

[BE/#267] 채팅 푸시 알림 전송 구현

---

BE/src/chat/chat.service.ts
BE/src/chat/chats.gateway.ts

[BE/#268] findRoomList 쿼리 수정

---

iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift

- #278 
- 게시글이 자신이 작성한 지의 유무에 따라 액션시트를 변경해줘야됨.
- 자신의 ID를 가지고 있는 지 의문이 들었음. 없다면 항상 가지고 있도록 고민해야 될 것 같음.

[iOS/#278] 액션시트를 활용한 편집, 삭제, 숨김, 차단 액션 구현

---

iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateTimeView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift

- #277
- isRequst와 isEdit이 View에 있었기 때문에 ViewModel에서 사용이 불가능했는데, 애초에 ViewModel에 있어야 맞는 인스턴스라고 생각하여 옮김.
- ViewModel 생성시에 request인지 edit 모드인지 정할 수 있도록 했음.

[iOS/#277] 게시글 편집 구현

---

BE/src/post/post.service.ts

- #272
- 무슨 이유로 어떻게 코드를 변경했는지
- 어떤 부분에 리뷰어가 집중해야 하는지
- 기술적 고민

[BE/#272] 게시글을 최신순으로 정렬하여 조회

---

BE/src/chat/chat.controller.ts
BE/src/chat/chat.service.ts
BE/src/chat/chats.gateway.ts

[BE/#276] 전송 성공 확인 메시지 응답 구현

---

BE/src/post/dto/postUpdate.dto.ts

[BE/#292] update dto에서 contents -> description 으로 수정

---

BE/src/entities/post.entity.ts
BE/src/post/post.service.ts

[BE/#292] 테이블 변경

---

BE/src/entities/post.entity.ts
BE/src/post/post.service.ts
BE/src/users/users.service.ts

[BE/#313] post 테이블 변경

---

BE/src/post/post.service.ts

[BE/#310] 작성자 id로 게시글 검색 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/BannedUser/BannedUserViewController.swift
iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift
iOS/Village/Village/Presentation/PostMute/PostMuteViewController.swift

[iOS/#280] 숨긴 게시글 및 차단 관리 화면으로 이동

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Dummy/PostMute.json
iOS/Village/Village/Domain/Network/PostMuteResponseDTO.swift
iOS/Village/Village/Presentation/PostMute/PostMuteTableViewCell.swift
iOS/Village/Village/Presentation/PostMute/PostMuteViewController.swift

[iOS/#284] 숨긴 게시글 뷰 구현 및 AutoLayout 적용

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Dummy/PostMute.json
iOS/Village/Village/Domain/Network/PostMuteResponseDTO.swift
iOS/Village/Village/Presentation/PostMute/PostMuteTableViewCell.swift
iOS/Village/Village/Presentation/PostMute/PostMuteViewController.swift

[iOS/#284] 숨긴 게시글 뷰 구현 및 AutoLayout 적용 다시 머지

---

BE/src/chat/chat.controller.ts
BE/src/chat/chat.service.ts
BE/src/chat/chats.gateway.ts
BE/src/chat/dto/chat.dto.ts
BE/src/entities/chat.entity.ts

[BE/#320] 채팅방 생성시 없는 게시물 404 , 채팅 count 수정

---

iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift
iOS/Village/Village/Presentation/MyPage/ViewModel/MyPageViewModel.swift

- #324 
- 아직 실제 로그아웃 로직은 작성되지 않았습니다.
https://github.com/boostcampwm2023/iOS05-Village/assets/19406851/daf50839-2ac1-4620-912b-9ab5263796f8

[iOS/#324] 로그아웃 UIAlertView 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Application/AppDelegate.swift
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Domain/Network/GetRoomResponseDTO.swift
iOS/Village/Village/Presentation/ChatList/View/ChatListViewController.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/ViewModel/ChatRoomViewModel.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Socket/WebSocket.swift

[iOS/#309] 채팅방 입장 시 로그 가져오기 구현

---

iOS/Village/Village/Network/EndPoint/Protocol/Requestable.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift

- #336
- Multipart는 body를 json으로 변환하지 않고 바로 적용시켜야 하는데 json 형식으로 변환하면서 post가 안되는 오류가 있었다. 
- json에서 오류가 나면 catch하여 바로 httpBody로 넣어줬다.

[iOS/#336] 게시글 등록 안되는 현상 제거

---

iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Presentation/MyPage/ViewModel/MyPageViewModel.swift

- #331 
- 현재 서버에서는 로그아웃 구현이 되지 않아 클라인트상의 코드만 구현됐고 실제 동작은 하지 않습니다.
없음

[iOS/#331] 로그아웃 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Domain/Network/UserResponseDTO.swift
iOS/Village/Village/Presentation/BlockedUser/View/BlockedUserTableViewCell.swift
iOS/Village/Village/Presentation/BlockedUser/View/BlockedUserViewController.swift
iOS/Village/Village/Presentation/BlockedUser/ViewModel/BlockedUserViewModel.swift
iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift

[iOS/#344] 차단 관리 뷰 구현 및 AutoLayout 적용

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/Commons/RentPostSummaryView.swift
iOS/Village/Village/Presentation/Commons/RequestPostSummaryView.swift
iOS/Village/Village/Presentation/Home/View/HomeCollectionViewCell.swift
iOS/Village/Village/Presentation/MyPosts/MyPostsViewController.swift
iOS/Village/Village/Presentation/MyPosts/RentPostTableViewCell.swift
iOS/Village/Village/Presentation/MyPosts/RequstPostTableViewCell.swift
iOS/Village/Village/Presentation/MyPosts/ViewModel/MyPostsViewModel.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift

- #340
- SegmentedControl 전환시 ViewModel과 binding을 고민했습니다. Control이 변경되면 ViewModel은 변경된 데이터를 최신순으로 불러오고 ViewController는 snapshot을 초기화하고 다시 ViewModel에서 받아옵니다.

[iOS/#340] 내 게시글 페이지네이션

---

BE/src/login/login.controller.ts
BE/src/login/login.service.ts

[BE/#348] 로그아웃 API 구현

---

iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Socket/WebSocket.swift

- #354 
- 엑세스토큰을 씌웠지만 토큰에 대한 이해도가 낮아서 추후에 리팩토링을 진행해야될 것 같다~~

[iOS/#354] 소켓통신 시, JWT 헤더에 적용

---

iOS/Village/Village/Presentation/MyPosts/ViewModel/MyPostsViewModel.swift

[iOS/#365] DTO 오류 해결

---

BE/src/post/post.controller.ts
BE/src/utils/files.validator.ts

- #358
- 파일을 안보내면 400이 날라와서 수정함

[BE/#358] max file validator 수정

---

BE/src/post/post.controller.ts
BE/src/users/users.controller.ts
BE/src/utils/files.validator.ts

[BE] 파일사이즈 검사 로직 수정

---

iOS/Village/Village/Presentation/Home/View/HomeCollectionViewCell.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/Home/ViewModel/HomeViewModel.swift

- #343 
- 새로고침의 경우에 대해 의논해봤고, 현재는 `viewWillAppear`에서 새로고침이 이뤄지도록 구현했습니다.
https://github.com/boostcampwm2023/iOS05-Village/assets/19406851/7071c596-6c84-4b0a-9888-b96b0fb105f1

[iOS/#343] 홈 화면으로 돌아왔을 때 새로고침

---

iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift

- #364
|![image](https://github.com/boostcampwm2023/iOS05-Village/assets/128480641/5764853d-5a3a-4884-80fc-9e425fb985bf)|![image](https://github.com/boostcampwm2023/iOS05-Village/assets/128480641/f2cf06d5-70f4-4e2b-b00a-5b145782f8fa)|![image](https://github.com/boostcampwm2023/iOS05-Village/assets/128480641/0715843c-6988-4dd9-941e-6c5d0d7f2c17)|
| --- | --- | --- |

[iOS/#364] 상세 화면 내 게시글 여부 확인

---

iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Domain/Network/GetChatListResponseDTO.swift
iOS/Village/Village/Domain/Network/GetRoomResponseDTO.swift
iOS/Village/Village/Presentation/ChatList/View/ChatListTableViewCell.swift
iOS/Village/Village/Presentation/ChatList/View/ChatListViewController.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/ViewModel/ChatRoomViewModel.swift
iOS/Village/Village/Socket/WebSocket.swift

[iOS/#371] 채팅목록에서 채팅방내역 API 연결 

---

BE/src/utils/fcmHandler.ts

- #380
- 토큰이 없는 경우 에러를 던져주던것이 gateway로 타고 올라가서 서버가 멈출수 있어 내부에서 잡도록 수정했다.

[BE/#380] 푸시 알림 오류 수정

---

iOS/Village/Village/Presentation/Home/ViewModel/HomeViewModel.swift

- #391 
- 데이터를 요구하는 함수 호출이 동시에 여러번 되면서 뷰 모델에서 flag 변수에 대한 동기화 문제가 있었던 것으로 추측하고 있습니다. 
이를 방지하기 위해 lock을 추가했습니다.
- 페이지네이션 가장 끝에서도 요청이 이뤄진 뒤 빈 데이터를 받아오는 것에 대해 고려하지 못해서 예외처리를 해주지 못했습니다.
없음

[iOS/#391] 새로고침 페이지네이션 충돌 버그 수정

---

iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreatePriceView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift

- #393
- 작성하기 버튼은 없는게 낫다고 팀원과 상의 후에 판단

[iOS/#393] 게시글 등록 피드백 반영

---

iOS/Village/Village/Presentation/Commons/RentPostSummaryView.swift
iOS/Village/Village/Presentation/Home/View/HomeCollectionViewCell.swift
iOS/Village/Village/Presentation/MyPosts/View/RentPostTableViewCell.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreatePriceView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift

- #397 
- 가격 범위를 10억 밑으로 함.
- cell에서 가격에 천단위 , 을 넣음.

[iOS/#397] 게시글 등록 가격 설정 HotFix

---

BE/src/chat/chat.service.ts

- #385
- 기본 이미지 null 인 경우, 기본 이미지 url 전송
- chat/room/:id API 에 유저 이미지도 함께 전송

[BE/#385]  기본 이미지 url 전송

---

BE/src/users/users.service.ts

- #402
- iOS의 요청으로 방식을 변경하였다. 기본사진에서 프로필 사진이 선택되면 다시 기본 사진으로 돌아갈 수 없다는 전제하에 수정 하였다.

[BE/#402] 유저 수정 방식 변경

---

iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Socket/WebSocket.swift

[iOS/#400] 채팅방 receive 과정 디코딩 에러 수정

---

BE/src/login/login.controller.ts
BE/src/posts-block/posts-block.controller.ts
BE/src/posts-block/posts-block.service.ts

[BE/#423] 숨긴 게시글 응답 수정

---

iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Presentation/MyHiddenPosts/View/HiddenRentPostTableViewCell.swift
iOS/Village/Village/Presentation/MyHiddenPosts/View/HiddenRequestPostTableViewCell.swift
iOS/Village/Village/Presentation/MyHiddenPosts/View/MyHiddenPostsViewController.swift
iOS/Village/Village/Presentation/MyHiddenPosts/ViewModel/MyHiddenPostsViewModel.swift

- #427
- 버튼을 누를 때마다 Combine으로 통신

[iOS/#427] 숨긴 게시글 버튼으로 숨김 관리 구현

---

iOS/Village/Village/Application/AppDelegate.swift
iOS/Village/Village/Presentation/ChatList/View/ChatListViewController.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/ViewModel/ChatRoomViewModel.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift

[iOS/#435] 채팅방 버그 수정

---

BE/src/post/post.module.ts
BE/src/post/post.service.ts
BE/src/users/users.service.ts

[BE/#443] 유저 탈퇴시 게시글을 삭제 되지 않도록 수정

---

BE/src/chat/chat.controller.ts
BE/src/chat/chat.service.ts

[BE/#442] /chat/unread API 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Domain/Network/BlockedUserDTO.swift
iOS/Village/Village/Presentation/BlockedUser/View/BlockedUserTableViewCell.swift
iOS/Village/Village/Presentation/BlockedUser/View/BlockedUserViewController.swift
iOS/Village/Village/Presentation/BlockedUser/ViewModel/BlockedUserViewModel.swift
iOS/Village/Village/Presentation/BlockedUser/ViewModel/BlockedUsersViewModel.swift
iOS/Village/Village/Presentation/MyHiddenPosts/View/MyHiddenPostsViewController.swift
iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift

[iOS/#439] 차단한 사용자 차단 관리 구현

---

iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Domain/Network/GetChatListResponseDTO.swift
iOS/Village/Village/Presentation/ChatList/View/ChatListTableViewCell.swift
iOS/Village/Village/Presentation/ChatList/View/ChatListViewController.swift
iOS/Village/Village/Presentation/ChatList/ViewModel/ChatListViewModel.swift
iOS/Village/Village/Resources/Assets.xcassets/AlertColor.colorset/Contents.json

- #441 
- 알림 표시를 어디에 어떻게 할 지 고민
- 최근 채팅 오른쪽에 빨간점으로 결정

[iOS/#441] 채팅 목록 안읽은 알림 구현

---

iOS/Village/Village/Domain/Network/RequestFilterDTO.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreatePriceView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift

- #449
- Warning Label을 띄우기 위해 warning 구조체에 추가했습니다.

[iOS/#449] 대여 등록시 사진 필수 구현

---

iOS/Village/Village/Presentation/Commons/RentPostSummaryView.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/Search/SearchViewController.swift
iOS/Village/Village/Presentation/SearchResult/View/SearchResultViewController.swift

[iOS/#452] 검색화면에서 셀 클릭시 상세화면으로 이동

---

iOS/Village/Village/Presentation/ChatList/View/ChatListTableViewCell.swift
iOS/Village/Village/Presentation/ChatList/View/ChatListViewController.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomTableViewCell.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/View/OpponentChatTableViewCell.swift
iOS/Village/Village/Presentation/Commons/RentPostSummaryView.swift
iOS/Village/Village/Presentation/Commons/RequestPostSummaryView.swift

- #457 
- 채팅내역을 제일 최근의 내역으로 내릴 때, 내리면서 포스트뷰가 생성되어 다시 올라가는 현상발생

[iOS/#457] 채팅방 게시글 요청대여에 따른 postView 변경

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/MyPosts/View/RentPostTableViewCell.swift

- #461
- 제대로된 이미지가 들어온 경우 배경색이 변하지 않는 현상을 제거

[iOS/#461] 썸네일 배경 삭제

---

BE/package-lock.json
BE/package.json
BE/src/utils/ocrHandler.ts

- #467
- 추후 이미지 검색을 위해 OCR로직을 추가하였다. 아직 사용하는 곳은 없지만 추후 더 고도화된 검색을 위해 적용할 예정

[BE/#467] OCR 핸들러 클래스 구현

---

iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Socket/WebSocket.swift

[iOS/#482] 웹소켓 제대로 나가지도록 수정

---

BE/src/chat/chat.controller.ts
BE/src/chat/chat.service.ts

[BE/#487] 없는 유저나 게시글에 대해 채팅하려고 하면 오류 반환

---

iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift

- #499
- isLoading으로 버튼을 작동하지 못하도록 했다.

[iOS/#499] 버튼 여러번 누르지 못하도록 설정

---

iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift

[iOS/#506] PostView 불편함 해소

---

iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift
iOS/Village/Village/Presentation/MyPage/ViewModel/MyPageViewModel.swift

- #511
- 다른 기기에서 프로필을 수정했을 수도 있기 때문에 마이페이지에서 ViewWillAppear를 통해 새로고침을 해주도록 설정했다.

[iOS/#511] 프로필 수정 버튼 Combine 수정

---

iOS/Village/Village/Presentation/MyHiddenPosts/View/HiddenRentPostTableViewCell.swift
iOS/Village/Village/Presentation/MyHiddenPosts/View/HiddenRequestPostTableViewCell.swift

- #513
- Cell을 재사용 하는 경우 prepareForReuse를 꼭 쓰자...

[iOS/#513] 숨긴 게시글 하나 해제시 전체 게시글 숨김 해제 되는 현상 해결

---

BE/src/entities/post.entity.ts
BE/src/entities/report.entity.ts
BE/src/entities/user.entity.ts
BE/src/report/report.service.ts

- #519
- 무슨 이유로 어떻게 코드를 변경했는지
- 어떤 부분에 리뷰어가 집중해야 하는지
- 기술적 고민

[BE/#519]신고 API 수정

---

iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift

- #517
- 서버에서 사진데이터에 대해 서비스가 구축되면 상용화

[iOS/#517] 채팅 + 버튼 삭제

---

iOS/Village/Village/Common/NotificationName+.swift
iOS/Village/Village/Common/PostNotificationPublisher.swift
iOS/Village/Village/Presentation/BlockedUser/ViewModel/BlockedUsersViewModel.swift
iOS/Village/Village/Presentation/Home/ViewModel/HomeViewModel.swift
iOS/Village/Village/Presentation/MyHiddenPosts/ViewModel/MyHiddenPostsViewModel.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

[iOS/#523] 홈 사용자 차단 새로고침 추가

---

BE/src/post/post.service.ts

- #524
- 무슨 이유로 어떻게 코드를 변경했는지
- 어떤 부분에 리뷰어가 집중해야 하는지
- 기술적 고민

[BE] 차단 해제후 목록에서 안뜨는 에러 수정

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/ChatList/View/ChatListViewController.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/EditProfile/View/EditProfileViewController.swift
iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift
iOS/Village/Village/Presentation/SearchResult/View/SearchResultViewController.swift
iOS/Village/Village/Resources/Info.plist

[iOS/#529] 가로 화면 지원

---

iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/Home/ViewModel/HomeViewModel.swift

- #514 
- 어떻게 게시글 상세화면에서 숨김하고 돌아왔을 때 페이지네이션을 해줘야할지 고민했습니다.
- 기존 페이지네이션은 scrollViewDidScroll을 통해 이루어지다보니 스크롤이 되지 않으면 페이지네이션 로직이 아예 발동이 안 됐습니다.
- 셀이 재사용된다는 성질을 활용하여 보여질 셀의 indexPath가 데이터소스의 아이템 개수 끝과 차이가 얼마 안 날 때 뷰 모델에 페이지네이션 요청을 보내도록 수정했습니다.
- 끝에 도달하여 페이지네이션을 더 이상 진행하지 않는 검사는 뷰 모델 내부에서만 이뤄지도록 했습니다.

[iOS/#514] 홈화면 페이지네이션 로직 개선

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Cache/ImageCache.swift
iOS/Village/Village/Network/APIProvider/APIProvider.swift

- #533
- 디스크 캐싱에 대해서 고민, 사용자가 저장소를 사용하면서까지 캐싱을 해야되는지 의문
- 메모리 캐싱만 고려하여 캐싱 처리를 구현

[iOS/#533] 이미지 캐싱

---

BE/src/posts-block/users-block.service.spec.ts
BE/src/users-block/users-block.service.spec.ts

- #537
- nest에서 처음 단위 테스트를 작성하여서 어려웠다. 그래도 이번에 성공했기 때문에 다음 부터는 테스트 코드작성이 쉬워질 것 같다.

[BE/#537] block-post.service 단위 테스트 코드 작성

---

BE/src/common/decorator/auth.decorator.ts
BE/src/common/guard/auth.guard.ts
BE/src/common/interceptor/httpLogger.interceptor.ts
BE/src/login/login.service.ts
BE/src/users-block/users-block.service.ts
BE/src/users/users.service.ts

- #540
- 아직 실 서비스를 돌려본 경험은 없어서 일단 개발하면서 느꼈던 불편했던 점만 로깅 하였다. 어떤 유저가 어떤 작업을 했는지는 나중에 분석 할 때 필요할 것 같아 로깅 하였다.

[BE/#540] 로깅 추가

---

iOS/Village/Village/Application/AppTabBarController.swift

- #551 
없음
<image src = "https://github.com/boostcampwm2023/iOS05-Village/assets/19406851/e4f6a325-6ff1-40f7-b286-e1e9e16ff959" width = "400" />

[iOS/#551] 탭바 Divider 있도록 수정

---

BE/src/login/login.service.ts

[BE] refresh token 만료시 401 응답

---

BE/src/common/guard/auth.guard.ts

[BE] access token 만료시 401 응답

---

iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift
iOS/Village/Village/Presentation/MyPage/ViewModel/MyPageViewModel.swift

- #565
- 비동기 처리 후에 새로고침 할 수 있도록 수정

[iOS/#565] 마이페이지 버그 수정

---

iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/ViewModel/ChatRoomViewModel.swift

[iOS] 채팅 핫픽스

---

iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreatePriceView.swift

[iOS] 가격단위 HotFix

---

BE/src/post/dto/postList.dto.ts
BE/src/post/post.repository.spec.ts
BE/src/post/post.repository.ts
BE/src/post/post.service.ts

- #585
- 이미지 배열대신 대표 이미지 한장만 응답
- page 대신 cursorId 로 수정
- description 등 불필요한 데이터 제거

[BE/#585] post list api 수정

---

BE/src/post/post.service.spec.ts
BE/src/post/post.service.ts

[BE/#593] post service 테스트 코드 작성

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Data/Network/DTO/ChatListItemDTO.swift
iOS/Village/Village/Data/Network/DTO/ChatListResponseDTO.swift
iOS/Village/Village/Data/Repository/DefaultChatListRepository.swift
iOS/Village/Village/Domain/Entity/ChatList.swift
iOS/Village/Village/Domain/Repository/ChatListRepository.swift
iOS/Village/Village/Domain/UseCase/ChatListUseCase.swift
iOS/Village/Village/Presentation/ChatList/View/ChatListTableViewCell.swift
iOS/Village/Village/Presentation/ChatList/View/ChatListViewController.swift
iOS/Village/Village/Presentation/ChatList/ViewModel/ChatListViewModel.swift

- #594 
- 이렇게 하는 게 맞겠죠 ///??
- 네트워크 통신 간 에러라고 판단해서 NetworkError로 수정
- 상윤님 같은 경우에 getListItem이라는 entity를 설정해서 구현을 했는데, 안의 구조가 DTO와 같은데 굳이 엔티티로 구별하는 이유를 모르겠습니다. 하ㅏ하..

[iOS/#594] 채팅목록 Clean Architecture 도입

---

BE/src/users-block/users-block.controller.ts
BE/src/users-block/users-block.service.ts

[BE/#609] 채팅 차단 확인 API

---

BE/src/chat/chat.service.ts

[BE/hotfix] chat/unread 수정
