boostcampwm2023/iOS05-Village

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/CustomView/FloatingButton.swift

- close #8 
- UIButton을 상속 받을지 UIView를 상속 받을지 고민했습니다. Floating Button은 특수한 UIButton이라고 생각해서 UIButton을 상속 받는 것으로 결정했습니다.
- Floating Button의 생김새 변화 코드는 버튼 자체의 기능이기 때문에 상위에서 addTarget하는 로직에서 내부에서 addAction하도록 수정했습니다. addAction을 사용한 이유는 코드가 간단하기 때문에 별도의 @objc 함수를 선언하지 않고 클로저로 바로 넣기 위함입니다.
- 많은 고민 끝에 버튼이 눌렸을 때 표시될 메뉴를 표시/숨기기 하는 것은 상위 뷰 컨트롤러에서의 책임이라고 생각했습니다. 버튼은 상위에 대한 정보를 몰라야 하기 때문입니다. 그래서 버튼의 트리거 값에 따른 동작을 상위에서 정의할 수 있도록 @Published 프로퍼티 래퍼를 통해 toggle 값을 구독하여 반응할 수 있도록 코드를 작성했습니다.
- 임시 동작 확인 
<image src="https://github.com/boostcampwm2023/iOS05-Village/assets/19406851/3f62a223-8385-4c34-8ec9-a3c0edcc8146" width="300" />

[iOS/#8] 홈 화면 게시글 등록 Floating Button 구현

---

iOS/Village/Village/Presentation/Home/View/HomeViewController.swift

- #70 
- 게시글 등록은 홈 화면(게시글 목록)의 흐름에 속하지 않는다 생각했기 때문에 `push`가 아닌 `present`를 했습니다.
- `modalPresentationStyle`을 `fullScreen`으로 지정한 이유는 스크롤을 하다 모달 뷰가 내려져 자칫 작성한 내용이 다 날아가는 불편함이 생길 가능성이 있기 때문입니다.
https://github.com/boostcampwm2023/iOS05-Village/assets/19406851/50a93b2a-1069-4af0-a543-3418b4d1ad97

[iOS/#70] 홈 화면 대여 게시글 등록 화면으로 이동

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Common/Constants.swift
iOS/Village/Village/Presentation/ChatRoom/ChatRoomViewController.swift
iOS/Village/Village/Presentation/Commons/PostSummaryView.swift
iOS/Village/Village/Presentation/Home/View/HomeCollectionViewCell.swift

- #82
- 홈 화면에서 사용한 뷰 구성이 동일하여 재사용하고 싶었음
- 공통 폴더를 하나 만들어서 재사용가능한 뷰로 구현

[iOS/#82] 채팅방 화면 UI 구현 및 오토레이아웃 적용

---

BE/package-lock.json
BE/package.json
BE/src/app.module.ts
BE/src/entities/post.entity.ts
BE/src/main.ts
BE/src/post/createPost.dto.ts
BE/src/post/post.controller.ts
BE/src/post/post.module.ts
BE/src/post/post.service.ts
BE/src/utils/multiPartBody.decorator.ts

- #issue_number
multipart 형식으로 이미지와 json을 같이 보내면 @Body() 데코레이터로 json 파싱이 되지 않는 문제가 발생하였다.
그래서 커스텀 데코레이터 @MultipartBody() 를 정의 하여 request 객체의 body를 JSON.parse 하여 사용 할 수 있도록 수정하였다.

[BE/#90] Post /posts API 구현

---

BE/src/post/post.controller.ts
BE/src/post/post.service.ts

- #102
- update 를 한번에 처리하려고 했는데 이전 데이터를 기억하는 방식이 아니라 한번에 덮었쓰는 방식이라 findOne 으로 진행함

[BE/#102] Feat : DeletePost 구현

---

BE/src/post/post.service.ts
BE/src/users/users.controller.ts
BE/src/users/users.module.ts
BE/src/users/users.service.ts
BE/src/users/usersUpdate.dto.ts
BE/src/utils/multiPartBody.decorator.ts

- #119
- nickname 수정 구현
- 프로필 사진 수정 구현
원래는 이미지에 대한 상태를 undefined, null 두개로 나누어서 undefined면 변경을 하지 않고 null이면 기본사진으로 변경하는 로직을 계획했었는데 file에 null을 넣어서 보낼 수 가 없었다. 그래서 json body에 이미지 수정 여부를 보내게 하여 처리하도록 수정하였다.

[BE/#119] PATCH /users/{id} API 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Domain/Network/PostRequestDTO.swift
iOS/Village/Village/Domain/Network/PostResponseDTO.swift
iOS/Village/Village/Network/EndPoint/EndPoint.swift
iOS/Village/Village/Network/Provider/Provider.swift
iOS/Village/Village/Presentation/DetailPost/PostDetailViewController.swift
iOS/Village/Village/Presentation/Home/View/HomeCollectionViewCell.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/Home/ViewModel/PostListItemViewModel.swift
iOS/Village/Village/Resources/Info.plist

- #110
- 내가 작성한 코드가 맞는 방식인지 아닌지 심히 고민됨..
- 여러군데에서 Provider를 사용할 것이라고 생각해서 싱글톤으로 생성
- 홈화면에서는 네트워크 통신 후, 뷰모델을 업데이트 한 뒤 다음 함수를 호출하여 컬렉션 뷰를 업데이트하는 방식으로 구현
- 추후에 페이지네이션을 통한 로직도 구현해야겠다고 생각.
~~~swift
configureDataSource()
generateData()
~~~

[iOS/#110] 네트워크 레이어 테스트

---

BE/src/entities/blockPost.entity.ts
BE/src/entities/post.entity.ts
BE/src/post/post.service.ts
BE/src/posts-block/posts-block.controller.ts
BE/src/posts-block/posts-block.service.ts

- #134
- 유저가 차단한 게시물의 목록을 반환하는 기능 구현
- 게시글 차단 코드에서 이미 존재하는지 확인하는 코드에 null 이 들어오면 에러 뜨는오류 수정
`isExist.status === true` 에서 isExist 에서 존재 하지 않으면 null 반환되고 null.status는 null이라고 생각하여 이렇게 구현했었는데 null에 프로퍼티를 찾는 연산을 하면 에러가 떴다.
그래서 null이면 조건문을 통과하도록 수정하였다.
엔티티를 정확하게 작성하지 않아 join이 되지 않는 오류가 발생하였다. 엔티티의 join 관계를 정확히 수정하니 정상적으로 작동하였다.
차단된 게시글의 내용과 게시글의 첫번째 사진을 반환해야했는데 사진을 또 찾으려면 3중 조인을 해야해서 비효율적이라 생각이 들어 게시글을 저장 할 떄 첫번째 사진은 게시글 테이블 안에 저장하도록 수정했다.

[BE/#134] GET /posts/block API 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/PostDetail/Custom/PriceLabel.swift
iOS/Village/Village/Presentation/Posting/View/Custom/PostingDetailView.swift
iOS/Village/Village/Presentation/Posting/View/Custom/PostingPriceView.swift
iOS/Village/Village/Presentation/Posting/View/Custom/PostingTimeView.swift
iOS/Village/Village/Presentation/Posting/View/Custom/PostingTitleView.swift
iOS/Village/Village/Presentation/Posting/View/PostingViewController.swift
iOS/Village/Village/Presentation/Posting/ViewModel/PostCreateViewModel.swift
iOS/Village/Village/Presentation/Posting/ViewModel/PostingRepository.swift
iOS/Village/Village/Presentation/Utils/Extensions/Int+.swift

- #146 
- 로직은 View가 아닌 ViewModel에 있어야 한다고 판단하여 View에 있는 로직을 ViewModel로 옮겼습니다.
- View의 변화는 ViewModel로 Combine을 통해서 전달되고 결과값을 반영하여 View에 영향을 줘야 할 때에는 Output으로 View를 변화시키기도 했습니다.

 [iOS/#146] 게시글 등록 View, ViewModel 바인딩

---

BE/src/entities/post.entity.ts
BE/src/post/post.controller.ts
BE/src/post/post.service.ts

- #167
- 게시글 0번째 부터 나오도록 수정
- 게시글 정보에서 유저 id 대시 hash 값이 들어가도록 수정
- 차단하는 게시글을 조회하는 경우 에러가 응답되도록 추가
-  post 엔티티에서 boolean 값들의 mysql 타입을 boolean으로 수정
- TypeORM에서 `@Column({ type: 'tinyint', nullable: false })` 과 같이 mysql 에서 boolean 타입이 없어서 tinyint로 설정했기에 엔티티에도 동일하게 설정하였더니 자료형이 boolean이 아니라 int 형으로 0, 1 이 저장되었다.
- 그래서 `@Column({ type: 'boolean', nullable: false })` 이렇게 타입을 변경하니 정상적으로 boolean 타입으로 반환되었다.
- 차단된 게시글의 상세화면의 요청에 대해서 예외처리를 할지 말지 고민 하였는데 우리의 iOS 클라이언트 외에도 요청이 들어올수 있기 때문에 예외 처리를 진행하였다.

게시글 조회 기능 구현

---

BE/src/entities/blockPost.entity.ts
BE/src/entities/blockUser.entity.ts
BE/src/entities/post.entity.ts
BE/src/entities/user.entity.ts
BE/src/post/post.controller.ts
BE/src/post/post.service.ts
BE/src/posts-block/posts-block.controller.ts
BE/src/posts-block/posts-block.service.ts
BE/src/users-block/users-block.controller.ts
BE/src/users-block/users-block.service.ts
BE/src/users/users.controller.ts
BE/src/users/users.module.ts
BE/src/users/users.service.ts
BE/src/utils/hashMaker.ts

- #118
- 유저나 게시글을 삭제 할 때 조인 되어있는 다른 데이터들이 한번에 삭제 되어야하는데 이것을 typeORM의 cascade 기능을 사용하여 구현하려 했지만 잘 동작이 되지 않아 수동으로 연관되어 있는 테이블의 데이터를 삭제하도록 구현하였다.

[BE/#118] DELETE API 구현 및 삭제 관련 로직 수정

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Common/Constants.swift
iOS/Village/Village/Presentation/SignUp/View/Custom/NicknameTextField.swift
iOS/Village/Village/Presentation/SignUp/View/Custom/ProfileImageView.swift
iOS/Village/Village/Presentation/SignUp/View/SignUpViewController.swift

- #195 
- 프로필 사진 UI 구현할 때 구석에 작은 카메라 넣는 것이 은근 까다로웠...
- 회원가입 로직이 바뀌어서 아마 마이페이지 화면으로 바뀔 것 같네요 하하핳
<image src="https://github.com/boostcampwm2023/iOS05-Village/assets/19406851/d68e2c3a-6bb9-4014-9bd0-5020601bea60" width=300>

[iOS/#195] 회원가입 화면 UI 구현

---

BE/src/login/login.controller.ts
BE/src/main.ts

- #216
- use global guard 사용하니까 모든 요청에 대해 가드 처리가 되어서 삭제하고 필요한 부분만 설정했다.

[BE] access token 검증 API 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/PersistentStorage/KeychainError.swift
iOS/Village/Village/Data/PersistentStorage/KeychainManager.swift

- #224 
- 키체인을 다루는게 처음이라 검색과 학습을 병행하면서 구현했습니다.
- 한 기기에 한 사용자의 토큰만 저장된다는 전제로 구현했다가, 다양한 계정에 대한 키체인이 다뤄지도록 애플 계정의 email을 쿼리의 `kSecAttrAccount`에 할당하도록 코드를 수정했습니다.
없음

[iOS/#224] 키체인 관리자 객체 구현

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Application/AppTabBarController.swift
iOS/Village/Village/Data/Dummy/ChatList.json
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/View/CustomView/PostView.swift
iOS/Village/Village/Presentation/Commons/PostSummaryView.swift
iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift
iOS/Village/Village/Presentation/MyPage/ViewModel/MyPageViewModel.swift

- #228 
- 마이페이지 레이아웃을 StackView로 잡았습니다. 추후에 요소가 많아질 경우 UITableView로 바꾸는 것을 고려해봐야할 것 같습니다.
- 네비게이션바와 탭바가 블러처리가 되는 현상이 있었습니다. 그래서 isTranslucent = false로 고쳤습니다.
- 채팅룸에서 채팅 cell끼리 sperator가 있는 것을 고쳤습니다.
- PrimaryColor를 지정하지 않은 ImageView가 있어서 수정했습니다. 
|다크모드 X|다크모드 O|
| --- | --- |
| <img width="599" alt="image" src="https://github.com/boostcampwm2023/iOS05-Village/assets/128480641/eaeb5e1f-1e54-432f-99ef-89629a02eb3b"> | <img width="599" alt="image" src="https://github.com/boostcampwm2023/iOS05-Village/assets/128480641/e70e8ab3-b279-493b-92c8-fdb6ad359fac"> |

[iOS/#228] 마이페이지 뷰 구현 및 AutoLayout 적용

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
iOS/Village/Village/Application/AppDelegate.swift
iOS/Village/Village/Application/GoogleService-Info.plist
iOS/Village/Village/Presentation/Utils/Extensions/NotificationName+.swift
iOS/Village/Village/Presentation/Utils/Extensions/UIView+Divider.swift
iOS/Village/Village/Resources/Info.plist

- #232
- 디바이스 토큰을 서버에 보내는 방법에 대해서 고민했습니다. 로그인을 했을 때 토큰을 같이 보내서 로그인이 만료됐을 때나 로그아웃을 했을 경우 디바이스 토큰을 같이 없애는 방법으로 구현해야 할 것 같습니다. 현재는 NotificationCenter를 이용하여 post로 토큰을 보내놓은 상태입니다. 로그인할 때 받아서 사용하면 됩니다.

[iOS/#232] 푸시 알림 Firebase 설정

---

iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateDetailView.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreatePriceView.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateTimeView.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateTitleView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

- #285
- 시간을 나타낼 때 서버에서 주는 것을 Date로 바꾸지 않고 사용하면 9시간 차이가 생긴다. Date로 한번 변환하고 사용해야 우리가 원하는 시간을 얻을 수 있다.
- 네트워크 API 통신을 한 뒤 DetailView를 업데이트 하기 위해서 UseCase를 나눠야 할 것 같다.

[iOS/#285] 편집시 View, ViewModel 업데이트

---

BE/package-lock.json
BE/package.json
BE/src/chat/chat.service.ts
BE/src/chat/chats.gateway.ts

- #299
- socket.io 와 다르게 nest의 가드가 적용되지 않아 직접 헤더에서 jwt를 추출해서 검사하는 로직을 추가하였다. 
- http로 403을 응답해주는 방법을 찾지 못해서 웹소켓의 연결을 끊고 1008 번을 주는 방식으로 구현하였다.

[BE/#299] 웹소켓 인가 처리

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Application/SceneDelegate.swift
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Data/PersistentStorage/JWTManager.swift
iOS/Village/Village/Data/PersistentStorage/KeychainManager.swift
iOS/Village/Village/Network/APIProvider/APIProvider.swift
iOS/Village/Village/Network/APIProvider/AuthInterceptor.swift
iOS/Village/Village/Presentation/Login/ViewModel/LoginViewModel.swift

- #303 
- JWT로부터 파싱한 유저 아이디를 저장하여 사용하는 것이 아직까지는 불가피해 보이기 때문에 save 시점에서 UserDefaults에 저장하도록 했습니다.
없음

[iOS/#303] JWT 키체인 유저 해시 아이디 저장 구현

---

BE/src/chat/chat.service.ts
BE/src/chat/chats.gateway.ts
BE/src/chat/dto/chat.dto.ts

[BE/#311] 채팅 읽음처리

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Domain/Network/PostRoomRequestDTO.swift
iOS/Village/Village/Domain/Network/PostRoomResponseDTO.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

- #287
- 방번호를 어디서 받아올 지 고민 -> 뷰모델에서 생성후 뷰컨트롤러에 번호를 넘겨주고 그 번호의 방으로 이동

[iOS/#287] 채팅하기 버튼 후 채팅방 생성

---

BE/src/users/users.service.ts

- #318
- 프로필 사진이 기본 사진이 일 때 db에 기본사진에 해당하는 사진 주소를 넣을까 고민했는데 이렇게 되면 기본사진인경우와 사진이 있는 경우를 구별하지 못 할 것 같았다. 그래서 db에는 널로 두되 클라이언트에 보낼 때만 기본 사진으로 사진을 대체 해서 보내는 방법을 선택했다.

[BE/#318] 프로필 기본 이미지 전송

---

iOS/Village/.swiftlint.yml
iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Domain/Network/PostModifyRequestDTO.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreatePriceView.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateTitleView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

- #301
- 편집 뷰로 들어갈 때 편집 뷰에 디테일 뷰의 내용을 적어주는 것을  중간에 글의 내용이 변할 수 있다고 판단하여 디테일 뷰에서 가져오지 않고 post id를 이용한 통신을 통해서 가지고 오도록 구현.
- 같은 이유로 편집후 디테일 뷰를 새로고침 해주는 것도 편집 뷰에서 가져오는 것이 아닌 서버에서 가져오도록 구현.

[iOS/#301] 편집 완료시 상세 페이지 새로고침

---

BE/src/post/post.service.ts

- #322
- 기존 오프셋 방식으로 하면 새로운 게시글이 추가되면 겹치는 문제점이 발생하여 압겹치도록 마지막으로 받은 게시글의 번호를 기준으로 그 아래에 엤는 게시글을 찾는 방식으로 수정하였다.

[BE/#322] 검색 구현 및 페이지네이션 수정

---

iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Data/PersistentStorage/JWTManager.swift
iOS/Village/Village/Presentation/MyPage/ViewModel/MyPageViewModel.swift

- #332
없음
https://github.com/boostcampwm2023/iOS05-Village/assets/19406851/5c0b42c0-b305-481f-92cb-6db0225c54ae

[iOS/#332] 회원 탈퇴 구현

---

BE/.dockerignore
BE/Dockerfile
BE/src/app.module.ts
BE/src/config/winston.config.ts
BE/src/main.ts

- #322
- 서버를 분리하기로 결정하였는데 모든 서버 마다 개발 환경을 설치하고 설정하는 것을 번거롭기 때문에 도커로 한번에 처리하기 위해 도커를 적용했다.
- 디버그 레벨의 로그 까지 전부 저장되도록 수정했다.

[BE/#322] 도커 적용 및 로그 변경

---

iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/ViewModel/ChatRoomViewModel.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

- #334
- PostDetailViewController로 넘어갈 때, 기존에는 postID, userID, isRequest 3개의 인자를 받는다
- postID에 나머지 두개가 포함되어있는 것을 확인하고 굳이 3개를 받을 필요를 느끼지 못했다.
- PostDetailViewController의 구조를 변경하고 postID만 가지고도 ViewController를 구현하도록 했다.
- 현재 저런식으로 이동하면 무한대로 push가 됨..

[iOS/#334] 채팅방에서 상세화면으로 이동

---

BE/src/chat/chats.gateway.ts

- #322
- iOS 에서 jwt 적용에 시간이 많이 걸려 이것보다 다른 기능 구현이 먼저라고 판단되어 임시로 비활성화 하였다.

[BE/#322] 웹소켓 인가처리 임시 비활성화

---

BE/src/chat/chats.gateway.ts
BE/src/post/post.controller.ts
BE/src/users/users.controller.ts

- #351 
- 파일 최대 용량 20MB 설정
- 채팅 주석 처리 삭제

[BE/#351] 파일 최대 용량 설정

---

BE/src/chat/chat.service.ts
BE/src/login/login.module.ts
BE/src/login/login.service.ts
BE/src/utils/fcmHandler.ts

- #358
- Injectable 클래스가 싱글톤 인 줄 알았는데 두 개의 모듈에서 사용 해보니 아니었다. firebase admin이 두번 초기화 되서 오류가 떴다. 
- 그래서 한번 초기화 된 다음에는 초기화 되지 않게 수정했다.

[BE/#358] registration token 삭제 구현

---

iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateDetailView.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreatePriceView.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateTimeView.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateTitleView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift
iOS/Village/Village/Presentation/PostDetail/Custom/PostInfoView.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

- #374
- 서버와 상세 페이지의 시간을 일치시키기 위해서 시간을 정수로 9시간을 뻬서 사용한다. 
- 종료시간이 앞선 경우 다른 warning을 띄우도록 설정했다.
전반적인 리팩토링을 조금 진행했다. 
비슷한 역할의 Input과 Output을 하나의 struct로 묶어서 보내도록 했다.

[iOS/#374] 시간 선택 로직 변경

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Data/PersistentStorage/FCMManager.swift
iOS/Village/Village/Domain/Network/PatchUserDTO.swift
iOS/Village/Village/Domain/Network/PostModifyRequestDTO.swift
iOS/Village/Village/Network/APIProvider/APIProvider.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift
iOS/Village/Village/Presentation/MyPage/ViewModel/MyPageViewModel.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateTimeView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/PostDetail/Custom/PostInfoView.swift
iOS/Village/Village/Presentation/SignUp/View/Custom/NicknameTextField.swift
iOS/Village/Village/Presentation/SignUp/View/Custom/ProfileImageView.swift
iOS/Village/Village/Presentation/SignUp/View/SignUpViewController.swift
iOS/Village/Village/Presentation/SignUp/ViewModel/SignUpViewModel.swift
iOS/Village/Village/Presentation/Utils/Extensions/UIImage+Resize.swift

- #384 
- 프로필 사진을 설정할 수 있다.
- 자신의 닉네임을 변경할 수 있다.
- 변경된 사항이 없다면 완료 버튼을 비활성화한다.
- 변경후 마이페이지를 새로고침한다.
- 사진을 선택하는 것이 권한이 꼭 필요한 줄 알았지만 PHPicker를 사용하면 권한이 필요없다는 것을 알게 됐습니다.
- View를 업데이트 할 때는 항상 DispatchQueue.main 에서 진행해야 합니다. 
- 이미지의 용량을 줄이기 위해서 원래 이미지에서 우리에게 꼭 필요한 크기로 사이즈를 줄이는 것을 구현했습니다.

[iOS/#384] 프로필 수정 구현

---

BE/src/chat/chat.service.ts

- #412
- 푸시 알림에 받는 사람 이름이 떠서 변경하였다.

[BE/#412] 푸시 알림에서 전송자 이름으로 변경

---

iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

- #409
- 숨기는 액션 처리로 숨기기 기능만 완료해 놓음
- 숨긴 뒤에 홈에서 보이지 않도록 처리함
- 게시글을 숨겼을 때, 채팅에서 그 게시글로 넘어가는 것도 막아야 함.

[iOS/#409] 게시글 숨기기 구현

---

BE/src/app.module.ts
BE/src/config/redis.config.ts
BE/src/login/login.controller.ts
BE/src/login/login.service.ts
BE/src/utils/auth.guard.ts

- #412
- 로그아웃시 해당 엑세스 토큰을 블랙리스트에 적용함
- 로그아웃시 registration token 삭제도 같이 일어나기 때문에 가드를 적용해서 유효한 엑세스 토큰을 가진 요청만 삭제되도록 수정
- 가드가 없으면 만료된 jwt로 악의적으로 사용자의 registration token을 삭제 할 수 있기 때문

[BE/#412] access token 블랙리스트 도입

---

iOS/Village/Village/Domain/Network/GetRoomResponseDTO.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomTableViewCell.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/View/OpponentChatTableViewCell.swift
iOS/Village/Village/Presentation/ChatRoom/ViewModel/ChatRoomViewModel.swift
iOS/Village/Village/Resources/Assets.xcassets/KeyboardTextFieldColor.colorset/Contents.json

- #388
- 뷰모델에 저장해주고 필요할때마다 데이터를 꺼내오는 방식으로 적용
- 이전의 채팅과 비교해서 다를 시에만 적용하도록 했는데 아래로 내릴때 프로필 사진이 적용되어있음.
- prepareForReuse를 적용해서 이미지를 nil로 바꿔주니 어느정도 해결됨
- 데이터를 아직 못불러왔을때는 프로필사진이 안뜸.. 해결방법 좀 알려주세요.. 고쉰ㅁ

[iOS/#388] 채팅방 프로필 사진 적용

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Common/Constants.swift
iOS/Village/Village/Domain/Network/PostModifyRequestDTO.swift
iOS/Village/Village/Presentation/PostCreate/Model/ImageItem.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/Cell/CameraButtonCell.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/Cell/ImageViewCell.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/ImageUploadView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift

- #69 
- PHPicker를 띄워주는 버튼을 가진 셀과 이미지를 표시하는 셀을 한 컬렉션뷰에서 사용하도록 했습니다.
- 카메라 버튼 셀의 버튼 동작은 뷰 컨트롤러로부터 넘겨받도록 구현했습니다.
- 선택된 사진 삭제는 따로 이슈를 파서 구현하겠습니다.
- 편집 화면에서 등록된 사진도 편집할 수 있도록 추가로 구현이 필요합니다.
https://github.com/boostcampwm2023/iOS05-Village/assets/19406851/bb4e7cbe-2b70-4a6b-872f-387c98a60f38

[iOS/#69] 대여 게시글 등록 화면 사진 등록 로직 구현

---

BE/src/login/login.controller.ts
BE/src/login/login.service.ts
BE/src/users/users.controller.ts
BE/src/users/users.module.ts
BE/src/users/users.service.ts

- #417
- 회원탈퇴하면 accessToken 블랙리스트 등록
- RefreshToken redis 등록

 [BE/#417] RefreshToken Redis 저장

---

BE/src/post/post.controller.ts
BE/src/post/post.service.ts

- #420
- 쿼리파람으로 들어온 키워드를 가지고 Like() 쿼리를 보내서 제목을 가져오고 그중 최신순으로 5개를 골라서 반환하도록 구현

[BE/#422] 제목 자동완성 API 구현

---

iOS/Village/Village/Common/Constants.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/Cell/CameraButtonCell.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/Cell/ImageViewCell.swift
iOS/Village/Village/Presentation/PostCreate/View/Custom/ImageUploadView.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift

- #421
- 처음에는 index를 통한 삭제로 구현했으나, 불안정하게 동작하면서 `index out of range`가 발생했습니다. 셀이 재사용되는 과정에서 삭제될 아이템의 index가 섞이는 문제였습니다.
그래서 `ImageItem` 모델을 통한 삭제로 다시 구현했습니다.
- 이미지는 최대 12장이므로 삭제 동작에서의 시간 복잡도는 신경쓰지 않았습니다.

[iOS/#421] 대여 게시글 등록 화면 선택 사진 삭제 구현

---

BE/src/chat/chat.service.ts

- #433 
- 
- 각 채팅방별로 안 읽은 메시지 존재여부는 가장 마지막 채팅의 읽음여부만 확인하면 된다

[BE] GET /chat/room API 수정

---

iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

- #436
- 상세페이지의 입장에서 사용자를 차단하고 게시글을 숨기는 것의 결과가 뷰를 pop 하는 것이기 때문에 같은 output을 사용했다.

[iOS/#436] 사용자 차단 구현

---

BE/src/chat/chat.service.ts

[BE/#433]  채팅방 읽음처리 재수정

---

iOS/Village/Village/Presentation/Search/SearchViewController.swift

- #450 
- 해당 속성을 지정해주지 않아 UISearchController가 활성화되있는 동안 사용자가 다른 뷰 컨트롤러로 이동했을 때 search bar가 남아있는 문제였던 것 같습니다.
없음

[iOS/#450] 홈 화면 사라지는 버그 수정

---

BE/src/app.module.ts
BE/src/config/mysql.config.ts
BE/src/entities/post.entity.ts
BE/src/entities/report.entity.ts
BE/src/entities/user.entity.ts
BE/src/report/createReport.dto.ts
BE/src/report/report.controller.ts
BE/src/report/report.module.ts
BE/src/report/report.service.ts

- close #458
- 추후에 신고관련해서 관리자에게 알림이 가는 기능이나 신고 누적 횟수가 일정이상이면 조치를 가하는 로직이 있으면 좋을 것 같다.

[BE/#458] 신고하기 API 구현 

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Domain/Network/ReportDTO.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Presentation/Report/View/ReportViewController.swift
iOS/Village/Village/Presentation/Report/ViewModel/ReportViewModel.swift

- #454
- 신고한 사용자를 차단해야 하는지 고민한 결과 다른 개시물을 보고싶을 수도 있기 때문에 자동으로 차단하는 기능은 뺐습니다.
|  ![image](https://github.com/boostcampwm2023/iOS05-Village/assets/128480641/fca575ac-d7d4-47d8-a333-2fc93df67c2b) |
| -------- |
|  ![image](https://github.com/boostcampwm2023/iOS05-Village/assets/128480641/fd991bdb-e6c3-4e4d-8ca4-741a6310c380)   |
| ![image](https://github.com/boostcampwm2023/iOS05-Village/assets/128480641/06df4f4e-0f3c-48ce-a5d5-bb9fc2fda520) |

[iOS/#454] 신고 구현

---

iOS/Village/Village/Presentation/Commons/Cell/RentPostTableViewCell.swift
iOS/Village/Village/Presentation/Commons/Cell/RequstPostTableViewCell.swift
iOS/Village/Village/Presentation/MyPosts/View/MyPostsViewController.swift
iOS/Village/Village/Presentation/MyPosts/ViewModel/MyPostsViewModel.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift

- #479
- 삭제, 편집시에 바깥 뷰컨에서 새로고침을 할 수 있도록 Combine을 사용했습니다.
- Cell이 재사용 될 때 이미지 로딩에 시간차가 생겨 다른 이미지가 잠시 나오는 현상이 있었는데 prepareForReuse를 통해 해결했습니다.

[iOS/#479] 내 게시글 편집/삭제 새로고침 안 되는 현상 제거

---

iOS/Village/Village/Presentation/PostCreate/View/Custom/PostCreateTimeView.swift

- #489
- 10년을 설정하기 위해서 60 * 60 * 24 * 365 * 10으로 계산했습니다.

[iOS/#489] 게시글 등록 max 날짜 설정

---

iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/SearchResult/View/SearchResultViewController.swift
iOS/Village/Village/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift

[iOS/#486] 검색결과 페이지네이션 요청 계속가는 버그 수정 

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Common/NotificationName+.swift
iOS/Village/Village/Common/PostNotificationPublisher.swift
iOS/Village/Village/Common/PostType.swift
iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
iOS/Village/Village/Presentation/Home/ViewModel/HomeViewModel.swift
iOS/Village/Village/Presentation/MyHiddenPosts/ViewModel/MyHiddenPostsViewModel.swift
iOS/Village/Village/Presentation/PostCreate/ViewModel/PostCreateViewModel.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

- #501 
- 마이페이지에서 게시글 숨김에 대한 변경이 일어났을 때, 홈에서 새로고침을 어떻게 해줘야할지에 대해 고민이 있었습니다.
- 현재는 게시글 숨김 화면이 dismiss 됐을 때 홈에서 대여/요청 모두 새로고침이 일어나도록 구현했습니다.
없음

[iOS/#501] 게시글 숨김 처리 했을 때 새로고침 구현

---

iOS/Village/Village/Presentation/PostDetail/Custom/UserInfoView.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift

- #504 
- 프로필사진 부분을 공백처리를 해도될지 모르겠지만 나쁘진 않은것같다.
<img src=https://github.com/boostcampwm2023/iOS05-Village/assets/59719500/7d1154f0-80d3-48a7-b6fb-c9bdd60928fa width=300 />

[iOS/#504] 유저 탈퇴 관련 이슈 구현

---

BE/src/post/post.service.ts
BE/src/users-block/users-block.service.ts
BE/src/users/users.service.ts

- #524
- 탈퇴한 사용자에 대해 조회될 때 null 값으로 어떻게 줄지 고민한결과 조인 된게 있는지 확인하여 처리 했다.

[BE/#524] 탈퇴한 사용자도 차단할 수 있도록 수정

---

iOS/Village/Village/Domain/Network/BlockedUserDTO.swift
iOS/Village/Village/Presentation/BlockedUser/View/BlockedUserTableViewCell.swift
iOS/Village/Village/Presentation/Report/View/ReportViewController.swift

- #518
- 탈퇴한 사용자를 신고하거나 차단하면 앱이 터지는 현상 발생 -> 서버 문제로 서버와 협의하여 DTO 수정
- 탈퇴한 사용자를 차단하면 차단 목록에서 받아올 때 nil 로 받아와야 하기 때문에 nil인경우 처리함

[iOS/#518] 탈퇴한 회원 신고, 차단

---

iOS/Village/Village/Presentation/SearchResult/View/SearchRentTableViewCell.swift
iOS/Village/Village/Presentation/SearchResult/View/SearchRequstTableViewCell.swift
iOS/Village/Village/Presentation/SearchResult/View/SearchResultViewController.swift
iOS/Village/Village/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift

- #516
- 통신결과가 없을 경우 기존의 셀이 사라지지않고 남아있는 버그가 생겼다.
- prepareForReuse를 활용해서 남아있지 않게 변경했다.
- prepareForReuse에 대해서 별 생각이 없었는데 활용을 많은 부분에서 해야겠다.
- deleteAllItems를 이용해서 초기화

[iOS/#516] 검색 결과 버그 수정

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/PostDetail/Custom/ImageDetailView.swift
iOS/Village/Village/Presentation/PostDetail/Custom/ImagePageView.swift
iOS/Village/Village/Presentation/PostDetail/PostDetailViewController.swift
iOS/Village/Village/Presentation/PostDetail/ViewModel/PostDetailViewModel.swift

- close #522 
- 이미지를 탭했을 때 디테일 뷰가 화면 전체로 나타나도록 하기 위해서 뷰 컨트롤러에서 기능이 동작하도록 했습니다.
- 이를 위해 ImagePageView에 이미지가 탭 됐을 때 해당 이미지의 데이터와 탭이 됐으니 디테일뷰를 띄우라는 것을 뷰 컨트롤러에서 바인딩하여 처리하도록 구현했습니다.
- 네비게이션 바까지 채우도록 시도해봤지만, 잘 안돼서 추후 개선점으로 남겨두겠습니다.

[iOS/#522] 이미지 상세화면 구현

---

iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift

- #531 
- constraints를 미리 80으로 잡아준 다음에, 포스트뷰가 생성될때 topAnchor를 다시 바꿔줌.
- 채팅창이 아래로 도착하기 전에 채팅창을 숨겨주고 도착했을 때, 채팅창을 나타나게해서 버벅임을 최소화함

[iOS/#531] 포스트뷰 때문에 채팅창 밀리는 버그 수정

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/EditProfile/View/EditProfileViewController.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift
iOS/Village/Village/Presentation/Utils/Extensions/NSItemProvider+.swift

- #541 
- 현재 저희 최소 지원 iOS가 15이기 때문에 loadDataRepresentation을 사용할 수 없었기 때문에 loadFileRepresentation을 사용해야 했습니다.
- loadObject를 또 다른 함수로 wrapping했기 때문에 비동기 이슈가 있었고, escaping completion을 통해 해결했습니다.
- 주의해야했던 점은 loadFileRepresentation은 기기 임시 폴더에 파일을 복사하여 데이터를 가져오는 방식이고, 임시 파일이 그대로 남아있게 됩니다. 그래서 fileprivate 함수로 파일을 삭제하는 로직을 추가로 구현했습니다.
- 우선 현재는 webp, heic, rawImage 포멧을 불러올 수 있도록 했습니다. 추후 다른 이미지 포멧 이슈가 생기면 추가하겠습니다.
- 이미지 파일 저장 캡쳐
- 삭제 동작 확인

[iOS/#541] PHPicker에서 특정 이미지 포멧 로드 안되는 문제 해결

---

iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/PostCreate/View/PostCreateViewController.swift

- #550
- isActive = fasle 후 새로 대입하고 isActive = ture 로 했었는데 constant만 변경하는 것으로 더 효율적인 상황이 됐습니다.

[iOS/#550] 키보드 constraint 동적 변화 수정

---

iOS/Village/Village/Application/SceneDelegate.swift
iOS/Village/Village/Network/APIProvider/AuthInterceptor.swift
iOS/Village/Village/Network/NetworkError.swift
iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift

- #557 
- 서버에서 refreshToken과 accessToken의 만료 모두 401 에러로 보내주기 때문에 만료 요청에서도 계속 401 처리로 빠지는 현상을 발견했습니다.
- 토큰 갱신 호출은 별개로 한번만 통신이 이뤄지도록 로직을 변경했습니다.
- AppDelegate에서 앱이 실행될 때 무조건 한번은 FCM 토큰을 서버에 보내기 때문에 SceneDelegate에서 따로 자동 로그인을 시도하지 않도록 변경했습니다.
없음

[iOS/#557] Refresh Token 만료 처리 수정

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Presentation/MyPage/View/MyPageTableViewCell.swift
iOS/Village/Village/Presentation/MyPage/View/MyPageViewController.swift
iOS/Village/Village/Presentation/MyPage/View/ProfileTableViewCell.swift
iOS/Village/Village/Presentation/MyPage/ViewModel/MyPageViewModel.swift

- #554
- 프로필의 내용을 서버에서 받아와 ViewModel에 저장하여 사용하는 것이 더 효율적이라고 판단.

[iOS/#554] 마이페이지 UITableView로 변경

---

BE/src/config/mysql.config.ts
BE/src/entities/blockUser.entity.ts
BE/src/entities/post.entity.ts
BE/src/post/post.module.ts
BE/src/post/post.repository.spec.ts
BE/src/post/post.repository.ts
BE/src/post/post.service.ts

- #577
- 기존에는 필터링을 게시글 목록 20개를 가져와서 필터링 하여 응답하는 방식이어서 차단된 게시글이 있다면 응답시 20개가 전부 안채워지는 문제가 있어 db에서 select 해 올떄 차단된 게시글을 필터링하여 20개 가져오도록 수정
- 게시글이 삭제될 때 연관된 테이블의 데이터를 cascade로 삭제되게 수정했다. 그래서 다른 레파지토리를 post service에서 의존하지 않게되었다.
- 게시글이 삭제될 때 연관된 모든 데이터가 같이 삭제 되어야 하기에 트랜잭션을 적용하여 원자성을 지키도록 수정 했다.

[BE/#577] 게시글 필터링 수정 및 레파지토리 분리

---

BE/src/common/base.repository.ts
BE/src/common/interceptor/transaction.interceptor.ts
BE/src/post/post.controller.ts
BE/src/post/post.repository.spec.ts
BE/src/post/post.repository.ts
BE/src/post/post.service.ts

- #580
- 여러 서비스를 사용 할 때 db 테이블이 연관되어 있는 작업을 한다면 사용하는 서비스들에 트랜잭션을 적용해야한다. 분리된 repository들에서 트랜잭션을 적용하기위해 base repository와 transaction interceptor 를 생성했다.
- 이렇게 구현 함으로써 이제 트랜잭션이 필요한 controller 에 transaction interceptor를 하는 것 만으로 간단하게 트랜잭션을 적용할 수 있게 되었다.

[BE/#580] 트랜잭션 방법 변경

---

BE/package-lock.json
BE/package.json
BE/src/app.module.ts
BE/src/common/S3Handler.ts
BE/src/common/greenEyeHandler.ts
BE/src/config/s3.config.ts
BE/src/image/image.module.ts
BE/src/image/image.service.spec.ts
BE/src/image/image.service.ts
BE/src/image/postImage.repository.ts
BE/src/post/post.controller.ts
BE/src/post/post.module.ts
BE/src/post/post.service.ts

- #579
- image에 대한 처리가 여러 모듈에서 이루어지고 있는데 공통으로 뺴서 관리하는 것이 편할 것 같아 모듈을 새로 만들었다.
- 테스트 시에도 의존성이 분리되어 더 테스트 하기 용이해졌다.
- 객체를 반환하는 메서드가 있고 반환된 메서드를 모킹하는 부분에서 애를 많이 먹었는데 이때 모킹에서 중요한 점은 객체를 반환시킬떄 항상 동일한 객체를 반환시켜야한다.

[BE/#579]이미지 서비스 분리

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Network/APIProvider/CombineAuthInterceptor.swift
iOS/Village/Village/Network/APIProvider/NetworkAPI.swift
iOS/Village/Village/Network/APIProvider/NetworkService.swift

- #591
- Interceptor 적용
Interceptor를 적용하는 과정에서 기존의 방식은 attempt 수를 밖에서 정해줘서 반복했다. 에러 처리와 combine operator를 사용하면서 내부에서 attempt를 관리하는 것이 편리하다고 판단하여 Interceptor 내부에서 attempt를 관리하도록 수정했다.
- Error 처리
Error 처리를 tryMap과 mapError를 사용하여 편리하게 처리한다고 생각되기도 한다. 하지만, AnyPublisher 형식을 맞춰야 했기 때문에 모든 에러를 NetworkError로 변환해줘야 했다. 이 부분이 Combine의 단점이라고 생각되기도 하여 추후에 개선할 부분이라고 생각된다.

[iOS/#591] Network Layer Combine을 사용할 수 있도록 수정

---

BE/src/chat/chat.service.ts
BE/src/entities/chatRoom.entity.ts

[BE/#576] 마지막 채팅 DB 에 함께 저장

---

iOS/Village/Village.xcodeproj/project.pbxproj
iOS/Village/Village/Data/Network/APIEndPoints.swift
iOS/Village/Village/Data/Network/DTO/ChatDTO.swift
iOS/Village/Village/Data/Network/DTO/ChatRoomResponseDTO.swift
iOS/Village/Village/Data/Network/DTO/UserResponseDTO.swift
iOS/Village/Village/Data/Repository/DefaultChatRoomRepository.swift
iOS/Village/Village/Data/Repository/DefaultPostDetailRepostory.swift
iOS/Village/Village/Data/Repository/DefaultPostListRepository.swift
iOS/Village/Village/Data/Repository/DefaultReportRepository.swift
iOS/Village/Village/Data/Repository/DefaultUserDetailRepository.swift
iOS/Village/Village/Domain/Entity/ChatRoomData.swift
iOS/Village/Village/Domain/Entity/PostDetail.swift
iOS/Village/Village/Domain/Entity/UserDetail.swift
iOS/Village/Village/Domain/Repository/ChatRoomRepository.swift
iOS/Village/Village/Domain/Repository/PostDetailRepository.swift
iOS/Village/Village/Domain/Repository/PostListRepository.swift
iOS/Village/Village/Domain/Repository/ReportRepository.swift
iOS/Village/Village/Domain/Repository/UserDetailRepository.swift
iOS/Village/Village/Domain/UseCase/ChatRoomUseCase.swift
iOS/Village/Village/Domain/UseCase/PostDetailUseCase.swift
iOS/Village/Village/Domain/UseCase/PostListUseCase.swift
iOS/Village/Village/Domain/UseCase/Protocol/UseCase.swift
iOS/Village/Village/Domain/UseCase/ReportUseCase.swift
iOS/Village/Village/Domain/UseCase/UserDetailUseCase.swift
iOS/Village/Village/Presentation/ChatRoom/View/ChatRoomViewController.swift
iOS/Village/Village/Presentation/ChatRoom/ViewModel/ChatRoomViewModel.swift
iOS/Village/Village/Presentation/Commons/RentPostSummaryView.swift
iOS/Village/Village/Presentation/Commons/RequestPostSummaryView.swift
iOS/Village/Village/Presentation/Home/ViewModel/HomeViewModel.swift
iOS/Village/Village/Presentation/Report/ViewModel/ReportViewModel.swift

- #597 
- .failure로 하고 .emptyData를 return하는 식으로 변경함.
- 다른 분들의 생각은 어떤 지 궁금합니다.
- 기존의 코드는 roomID를 이용해서 접근하고, 가져온 데이터를 따로 저장하지 않고 개별적으로 필요한 데이터를 다른 함수에 주입시켰다.
- 데이터를 저장하고, 그 저장한 데이터를 기반으로 작업을 진행하는 것에 대해서 고민을 했지만 좋은 방법이 떠오르질 않음
- 프로필 이미지를 가져오는 과정에서도 비동기로 호출하여 에러가 발생하여 임의로 고침 -> 같이 고민해주세요..

[iOS/#597] 채팅방 Clean Architecture 도입

---

BE/src/users/users.controller.ts
BE/src/users/users.service.spec.ts
BE/src/users/users.service.ts

[BE/#606] user service 테스트 코드 작성

---

BE/src/chat/chat.service.ts
BE/src/entities/chatRoom.entity.ts

- #603 
1. writer_hide 와 user_hide 는 writer 와 user 에게 현재 채팅방이 채팅방 목록에 뜨나 안 뜨나 를 나타낸다.
2. writer_left_time 과 user_left_time 은 마지막으로 writer 와 user 가 각각 마지막으x로 채팅방을 언제 나갔는지를 나타낸다.
- 기본적으로는 x_hide 는 false , x_left_time 은 null 이다. 
- 현재 내가 user 라고 가정하고 내가 채팅방을 나가면, user_hide 는 true , user_left_time 은 현재 시각이 기록된다. 
- 이후에 만약 상대방이 다시 채팅을 보내는 경우, user_hide 는 false 로 변한다. user_left_time 은 그대로 두는데 이는 내가 어느 채팅부터 확인해야하는지 확인하기 위해서이다.
- 채팅 목록을 가져올때는 user_left_time 이후의 채팅목록만 가져온다.
- 채팅방 목록을 가져올때는, user_hide 가 false 인 것만 가져온다. user_left_time 은 신경쓰지 않는다.

[BE/#603] 채팅방 나갔다가 들어오면 이전 채팅 안보이게 구현
